"""
Hybrid *envelope* (RSA-2048 OAEP-SHA256 + AES-256-GCM) used to protect **Bango PII on the wire**.

* Browser loads ``/static/keys/public.pem`` and sends ``{"encrypted_pii": "1...."}`` in
  ``POST /api/demo/register`` (no plaintext names/card in the JSON).
* The server decrypts with ``keys_only/private_demo.pem`` and merges the fields for validation.

The same one-line string format is generated by :func:`encrypt_envelope_json` (e.g. tests) and
by ``static/js/bango-crypto.js``. Debug with :file:`../tools/decrypt_telegram_pii.py` (envelope, not
channel-specific).
"""

from __future__ import annotations

import base64
import json
import logging
import os
import re
from pathlib import Path
from typing import Any

from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding, rsa
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_PUBLIC_PEM = PROJECT_ROOT / "frontend" / "static" / "keys" / "public.pem"
DEFAULT_PRIVATE_PEM = PROJECT_ROOT / "keys_only" / "private_demo.pem"


def _b64e(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def _b64d(s: str) -> bytes:
    pad = 4 - len(s) % 4
    if pad != 4:
        s += "=" * pad
    return base64.urlsafe_b64decode(s.encode("ascii"))


def _load_public_key(pem_path: Path):
    p = Path(pem_path)
    if not p.is_file():
        return None
    data = p.read_bytes()
    return serialization.load_pem_public_key(data, backend=default_backend())


def _load_private_key(pem_path: Path):
    p = Path(pem_path)
    if not p.is_file():
        return None
    return serialization.load_pem_private_key(
        p.read_bytes(), password=None, backend=default_backend()
    )


def build_sensitive_enrollment_dict(reg: dict[str, Any]) -> dict[str, Any]:
    """PII to embed in the JSON ciphertext (never log this dict)."""
    return {
        "fname": str(reg.get("fname") or "").strip(),
        "lname": str(reg.get("lname") or "").strip(),
        "phone": str(reg.get("phone") or "").strip(),
        "email": str(reg.get("email") or "").strip(),
        "personal_id": str(reg.get("personal_id") or "").strip(),
        "full_name": str(reg.get("full_name") or "").strip(),
        "card_number": str(reg.get("card_number") or "").strip(),
        "card_exp": str(reg.get("card_exp") or "").strip(),
        # ``app`` stores raw CVV digits in ``cvv_len`` (historical name).
        "cvv": str(reg.get("cvv_len") or ""),
    }


def encrypt_envelope_json(
    payload: dict[str, Any],
    *,
    public_key_path: Path | None = None,
) -> str | None:
    """
    Return a single-line envelope string, or None if the public key is missing / error.

    Format: ``1.<b64(rsa_oaep(aes_key))>.<b64(nonce)>.<b64(aes_gcm_ciphertext)><tag>…``
    """
    pk = _load_public_key(public_key_path or DEFAULT_PUBLIC_PEM)
    if pk is None:
        return None
    try:
        plain = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode(
            "utf-8"
        )
    except (TypeError, ValueError):
        return None
    if not isinstance(pk, rsa.RSAPublicKey):
        return None
    aes_key = os.urandom(32)
    nonce = os.urandom(12)
    aesgcm = AESGCM(aes_key)
    ct = aesgcm.encrypt(nonce, plain, None)
    try:
        enc_key = pk.encrypt(
            aes_key,
            padding.OAEP(
                mgf=padding.MGF1(algorithm=hashes.SHA256()),
                algorithm=hashes.SHA256(),
                label=None,
            ),
        )
    except Exception as e:
        logger.warning("rsa envelope encrypt (RSA wrap): %s", e)
        return None
    return f"1.{_b64e(enc_key)}.{_b64e(nonce)}.{_b64e(ct)}"


def decrypt_envelope_string(
    blob: str,
    *,
    private_key_path: Path | None = None,
) -> dict[str, Any] | str:
    """
    Decrypt an envelope; returns dict (JSON) on success, or an error string.
    """
    private_key = _load_private_key(private_key_path or DEFAULT_PRIVATE_PEM)
    if private_key is None:
        return f"private key not found: {private_key_path or DEFAULT_PRIVATE_PEM}"
    s = re.sub(r"\s+", "", blob.strip(), flags=re.UNICODE)
    parts = s.split(".")
    if len(parts) != 4 or parts[0] != "1":
        return "invalid envelope: expected 4 parts starting with 1"
    try:
        enc_key, nonce, ct = (_b64d(parts[1]), _b64d(parts[2]), _b64d(parts[3]))
    except (ValueError, OSError) as e:
        return f"base64: {e}"
    try:
        sk = private_key
        if not isinstance(sk, rsa.RSAPrivateKey):
            return "not an RSA private key"
        aes_key = sk.decrypt(
            enc_key,
            padding.OAEP(
                mgf=padding.MGF1(algorithm=hashes.SHA256()),
                algorithm=hashes.SHA256(),
                label=None,
            ),
        )
    except Exception as e:
        return f"RSA decrypt: {e}"
    if len(aes_key) != 32:
        return "wrong AES key size after unwrap"
    try:
        plain = AESGCM(aes_key).decrypt(nonce, ct, None)
    except Exception as e:
        return f"AES-GCM: {e}"
    try:
        return json.loads(plain.decode("utf-8"))
    except (UnicodeError, json.JSONDecodeError) as e:
        return f"JSON: {e}"


# Keys allowed inside the encrypted JSON (browser ↔ server; ``cc``/``exp``/``cvv`` match the form)
PII_BUNDLE_ALLOWED_KEYS: frozenset[str] = frozenset(
    {
        "fname",
        "lname",
        "phone",
        "email",
        "personal_id",
        "full_name",
        "cc",
        "exp",
        "cvv",
        "card_number",
        "card_exp",
    }
)


def private_key_path_for_bango_pii() -> Path:
    """
    ``DEMO_BANGO_PII_DECRYPT_PEM`` overrides the default ``keys_only/private_demo.pem`` when the
    server must read client-wrapped PII.
    """
    p = (os.environ.get("DEMO_BANGO_PII_DECRYPT_PEM") or "").strip()
    if p:
        return Path(p).expanduser()
    return DEFAULT_PRIVATE_PEM


def apply_decrypted_pii_to_request(
    data: dict[str, Any], *, private_key_path: Path | None = None
) -> str | None:
    """
    If ``data`` has non-empty string ``encrypted_pii``, decrypt in-place and merge PII
    (only :data:`PII_BUNDLE_ALLOWED_KEYS`).

    Returns ``None`` on success; when no ``encrypted_pii`` or empty string, also ``None`` (caller
    uses existing plaintext body fields, e.g. unit tests, curl). On failure returns an error string
    (not shown to the client in full, only a prefix in JSON).
    """
    enc = data.get("encrypted_pii")
    if not isinstance(enc, str) or not enc.strip():
        return None
    pth = private_key_path or private_key_path_for_bango_pii()
    out = decrypt_envelope_string(enc.strip(), private_key_path=pth)
    if isinstance(out, str):
        return out
    if not isinstance(out, dict):
        return "invalid JSON payload in envelope"
    for k, v in out.items():
        if k not in PII_BUNDLE_ALLOWED_KEYS:
            continue
        if isinstance(v, (dict, list)):
            continue
        data[k] = v
    if not (data.get("cc") or "").strip() and (out.get("card_number") or "").strip():
        data["cc"] = str(out.get("card_number") or "").strip()
    if not (data.get("exp") or "").strip() and (out.get("card_exp") or "").strip():
        data["exp"] = str(out.get("card_exp") or "").strip()
    return None
