#!/usr/bin/env bash
#
# educational_demo — server install WITHOUT Docker
# - Ubuntu/Debian (root)
# - Python venv + Gunicorn (Unix socket)
# - Nginx reverse proxy
# - Let’s Encrypt via Certbot + Cloudflare DNS-01
#
# Usage (as root, from repo root or any path with REPO in env):
#   sudo bash deploy/install-native.sh
#
# Before running: A/AAAA in Cloudflare (or your DNS) should point to this server for $DOMAIN
#   so traffic works after install (TLS is issued via API, not HTTP-01).
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOG() { echo "[install-native] $*"; }
ERR() { echo "[install-native] ERROR: $*" >&2; }

if [ "$(id -u)" -ne 0 ]; then
  ERR "Run as root (sudo)."
  exit 1
fi

if [ ! -f "$REPO_ROOT/backend/app.py" ]; then
  ERR "Not the project root: $REPO_ROOT"
  exit 1
fi

if ! command -v apt-get >/dev/null 2>&1; then
  ERR "apt-get not found (this script targets Debian/Ubuntu)."
  exit 1
fi

read -r -p "Full domain (must match a Cloudflare zone, e.g. lab.example.com): " DOMAIN
DOMAIN="${DOMAIN// /}"
if [ -z "$DOMAIN" ]; then ERR "DOMAIN empty."; exit 1; fi

read -r -p "Email for Let’s Encrypt (account + expiry notices): " EMAIL_LE
[ -n "$EMAIL_LE" ] || { ERR "Email required."; exit 1; }

read -r -p "Cloudflare API token (Zone: DNS Edit for this domain’s zone): " CF_TOKEN
[ -n "$CF_TOKEN" ] || { ERR "Cloudflare token required."; exit 1; }

export DEBIAN_FRONTEND=noninteractive
LOG "Installing OS packages (nginx, certbot, python, …)…"
apt-get update -y
apt-get install -y --no-install-recommends \
  nginx \
  certbot \
  python3-venv \
  python3-pip \
  curl \
  ca-certificates \
  gettext-base

# Certbot Cloudflare plugin (package name on Ubuntu 22.04+)
if ! dpkg -s python3-certbot-dns-cloudflare &>/dev/null; then
  if apt-get install -y python3-certbot-dns-cloudflare 2>/dev/null; then
    : ok
  else
    LOG "python3-certbot-dns-cloudflare missing from apt; trying pip (break-system on supported systems)…"
    pip3 install --break-system-packages 'certbot-dns-cloudflare' 2>/dev/null \
      || pip3 install 'certbot-dns-cloudflare' 2>/dev/null \
      || { ERR "Install certbot-dns-cloudflare (apt or pip) and re-run."; exit 1; }
  fi
fi

VENV="$REPO_ROOT/.venv"
if [ ! -d "$VENV" ]; then
  LOG "Creating venv at $VENV"
  python3 -m venv "$VENV"
fi
# shellcheck disable=SC1091
source "$VENV/bin/activate"
pip install --upgrade pip
pip install -r "$REPO_ROOT/requirements-native.txt"
deactivate

mkdir -p "$REPO_ROOT/keys_only"
if [ -x "$REPO_ROOT/gen_keys.sh" ] && { [ ! -f "$REPO_ROOT/keys_only/private_demo.pem" ] || [ ! -f "$REPO_ROOT/frontend/static/keys/public.pem" ]; }; then
  LOG "Running gen_keys.sh (Bango PII)…"
  (cd "$REPO_ROOT" && ./gen_keys.sh)
fi
chown -R www-data:www-data "$REPO_ROOT" || true

CF_INI="/etc/letsencrypt/cloudflare-$DOMAIN.ini"
umask 077
{
  echo "# Cloudflare DNS-01 (generated by install-native.sh)"
  echo "dns_cloudflare_api_token = $CF_TOKEN"
} > "$CF_INI"
chmod 600 "$CF_INI"
LOG "Wrote $CF_INI (mode 600)"

if [ ! -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]; then
  LOG "Requesting certificate (DNS-01) for $DOMAIN…"
  certbot certonly \
    --non-interactive --agree-tos \
    -m "$EMAIL_LE" \
    --dns-cloudflare \
    --dns-cloudflare-credentials "$CF_INI" \
    -d "$DOMAIN" || { ERR "certbot failed. Check token (Zone.DNS:Edit) and that DOMAIN is in that zone."; exit 1; }
else
  LOG "Certificate already present under /etc/letsencrypt/live/$DOMAIN — skipping certbot"
fi

export DOMAIN
if ! command -v envsubst >/dev/null; then
  apt-get install -y gettext-base
fi
envsubst '$DOMAIN' < "$REPO_ROOT/deploy/nginx-site.conf.in" > /etc/nginx/sites-available/educational_demo
ln -sf /etc/nginx/sites-available/educational_demo /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default
nginx -t

UNIT_SRC="$REPO_ROOT/deploy/educational-demo.gunicorn.service"
UNIT_DST="/etc/systemd/system/educational-demo-gunicorn.service"
sed "s|REPO_ROOT_PLACEHOLDER|$REPO_ROOT|g" "$UNIT_SRC" > "$UNIT_DST"
chmod 644 "$UNIT_DST"

# Minimal .env if missing (Flask)
if [ ! -f "$REPO_ROOT/.env" ] && [ -f "$REPO_ROOT/.env.example" ]; then
  LOG "Copying .env from .env.example — edit FLASK_SECRET_KEY and secrets if needed"
  install -m 600 -o www-data -g www-data "$REPO_ROOT/.env.example" "$REPO_ROOT/.env" || true
  # set DOMAIN/DJANGO not required for base Flask; session secret matters
  if ! grep -q "^FLASK_SECRET_KEY=" "$REPO_ROOT/.env" 2>/dev/null; then
    echo "FLASK_SECRET_KEY=$(openssl rand -hex 32)" >> "$REPO_ROOT/.env"
  fi
  chown www-data:www-data "$REPO_ROOT/.env" || true
  chmod 600 "$REPO_ROOT/.env" || true
fi

systemctl daemon-reload
systemctl enable --now educational-demo-gunicorn.service
systemctl reload nginx || systemctl restart nginx

LOG "Done."
LOG "  • Gunicorn: systemctl status educational-demo-gunicorn"
LOG "  • Logs:     journalctl -u educational-demo-gunicorn -f"
LOG "  • Site:     https://$DOMAIN/start"
LOG "  • Renew:    add cron: certbot renew && systemctl reload nginx"
